steps:
  # Step 1: Install dependencies in a virtual environment
  - name: 'python:3.9'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          python -m venv venv && \
          . venv/bin/activate && \
          pip install --upgrade pip && \
          pip install -r requirements.txt

  # Step 2: Run tests in the same environment
  - name: 'python:3.9'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          python -m venv venv && \
          . venv/bin/activate && \
          pip install --upgrade pip && \
          pip install -r requirements.txt && \
          python -m unittest discover tests

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/my-project-batch-1-465611/souvik-registry/myapp:$BUILD_ID'
      - '.'

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/my-project-batch-1-465611/souvik-registry/myapp:$BUILD_ID'

images:
  - 'us-east1-docker.pkg.dev/my-project-batch-1-465611/souvik-registry/myapp:$BUILD_ID'

logsBucket: 'gs://lab1-static-site-souvik'
